import type { NextPage } from 'next';
import Head from 'next/head';

import Sidebar from '../components/Sidebar';

const Home: NextPage = () => {
  return (
    <main style={{ display: 'flex' }}>
      <Head>
        <title>WhatsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <Sidebar />
    </main>
  );
};

export default Home;
